/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 18
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 14
#define ALIAS_COUNT 0
#define TOKEN_COUNT 7
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_tripleDash = 1,
  anon_sym_source_COLON = 2,
  anon_sym_LF = 3,
  anon_sym_expression_COLON = 4,
  sym_restOfLine = 5,
  aux_sym_body_token1 = 6,
  sym_source_file = 7,
  sym_header = 8,
  sym_headerContent = 9,
  sym_headerSource = 10,
  sym_headerExpression = 11,
  sym_body = 12,
  aux_sym_body_repeat1 = 13,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_tripleDash] = "tripleDash",
  [anon_sym_source_COLON] = "source: ",
  [anon_sym_LF] = "\n",
  [anon_sym_expression_COLON] = "expression: ",
  [sym_restOfLine] = "restOfLine",
  [aux_sym_body_token1] = "body_token1",
  [sym_source_file] = "source_file",
  [sym_header] = "header",
  [sym_headerContent] = "headerContent",
  [sym_headerSource] = "headerSource",
  [sym_headerExpression] = "headerExpression",
  [sym_body] = "body",
  [aux_sym_body_repeat1] = "body_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_tripleDash] = sym_tripleDash,
  [anon_sym_source_COLON] = anon_sym_source_COLON,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_expression_COLON] = anon_sym_expression_COLON,
  [sym_restOfLine] = sym_restOfLine,
  [aux_sym_body_token1] = aux_sym_body_token1,
  [sym_source_file] = sym_source_file,
  [sym_header] = sym_header,
  [sym_headerContent] = sym_headerContent,
  [sym_headerSource] = sym_headerSource,
  [sym_headerExpression] = sym_headerExpression,
  [sym_body] = sym_body,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_tripleDash] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_source_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_expression_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_restOfLine] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_body_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_headerContent] = {
    .visible = true,
    .named = true,
  },
  [sym_headerSource] = {
    .visible = true,
    .named = true,
  },
  [sym_headerExpression] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(25);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == 'e') ADVANCE(23);
      if (lookahead == 's') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(26);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(27);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(29);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(1);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(6);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(4);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(5);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(16);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 17:
      if (lookahead == 'p') ADVANCE(18);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 20:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 21:
      if (lookahead == 's') ADVANCE(20);
      END_STATE();
    case 22:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 23:
      if (lookahead == 'x') ADVANCE(17);
      END_STATE();
    case 24:
      if (eof) ADVANCE(25);
      if (lookahead == '\n') SKIP(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_tripleDash);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_source_COLON);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_expression_COLON);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_restOfLine);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_restOfLine);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_body_token1);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_body_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(32);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 24},
  [4] = {.lex_state = 24},
  [5] = {.lex_state = 24},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 24},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_tripleDash] = ACTIONS(1),
    [anon_sym_source_COLON] = ACTIONS(1),
    [anon_sym_expression_COLON] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(7),
    [sym_header] = STATE(3),
    [sym_tripleDash] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(5), 1,
      anon_sym_source_COLON,
    STATE(6), 1,
      sym_headerSource,
    STATE(9), 1,
      sym_headerContent,
  [10] = 3,
    ACTIONS(7), 1,
      aux_sym_body_token1,
    STATE(4), 1,
      aux_sym_body_repeat1,
    STATE(10), 1,
      sym_body,
  [20] = 3,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      aux_sym_body_token1,
    STATE(5), 1,
      aux_sym_body_repeat1,
  [30] = 3,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      aux_sym_body_token1,
    STATE(5), 1,
      aux_sym_body_repeat1,
  [40] = 2,
    ACTIONS(18), 1,
      anon_sym_expression_COLON,
    STATE(14), 1,
      sym_headerExpression,
  [47] = 1,
    ACTIONS(20), 1,
      ts_builtin_sym_end,
  [51] = 1,
    ACTIONS(22), 1,
      sym_restOfLine,
  [55] = 1,
    ACTIONS(24), 1,
      sym_tripleDash,
  [59] = 1,
    ACTIONS(26), 1,
      ts_builtin_sym_end,
  [63] = 1,
    ACTIONS(28), 1,
      anon_sym_LF,
  [67] = 1,
    ACTIONS(30), 1,
      aux_sym_body_token1,
  [71] = 1,
    ACTIONS(32), 1,
      sym_restOfLine,
  [75] = 1,
    ACTIONS(34), 1,
      sym_tripleDash,
  [79] = 1,
    ACTIONS(36), 1,
      anon_sym_expression_COLON,
  [83] = 1,
    ACTIONS(38), 1,
      anon_sym_LF,
  [87] = 1,
    ACTIONS(40), 1,
      sym_tripleDash,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 10,
  [SMALL_STATE(4)] = 20,
  [SMALL_STATE(5)] = 30,
  [SMALL_STATE(6)] = 40,
  [SMALL_STATE(7)] = 47,
  [SMALL_STATE(8)] = 51,
  [SMALL_STATE(9)] = 55,
  [SMALL_STATE(10)] = 59,
  [SMALL_STATE(11)] = 63,
  [SMALL_STATE(12)] = 67,
  [SMALL_STATE(13)] = 71,
  [SMALL_STATE(14)] = 75,
  [SMALL_STATE(15)] = 79,
  [SMALL_STATE(16)] = 83,
  [SMALL_STATE(17)] = 87,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [18] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [20] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [22] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 3, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headerContent, 2, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headerSource, 3, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headerExpression, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_snap(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "snap",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
